import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { BarChart3, ChevronDown, Plus } from 'lucide-react'
import { listSets,getSet,listSeries,getSeries,type SeriesSummary,type SetDetail,type SetSummary,type SetCard } from '../api/sets'
import { CatalogueImage } from './CatalogueImage'
import type { CollectionDocument,CollectionEntry } from '../domain/collection'
import { printingKey,upsertEntry } from '../domain/collection'
import { CardEditor } from './CardEditor'
import { CardDetailsModal } from './CardDetailsModal'
import { SeriesComparison } from './SeriesComparison'
import {CardShowcase} from './CardShowcase'
import { useCardPrices } from '../hooks/useCardPrices'
import { money } from '../utils/money'
import { normalizeSearch,sortCatalogueCards,type CardSort } from '../domain/catalogue'
import {getGradingInterest} from '../domain/grading'
import type {FavoriteCard,FavoriteInput} from '../domain/favorites'
import {FavoriteButton} from './FavoriteButton'

const VIEW_KEY='pv-collection-view-v1',RECENT_KEY='pv-recent-sets-v1'
const languages=[['fr','FR'],['en','EN'],['ja','JP'],['zh-tw','ZH']] as const
const isOwned=(entry:CollectionEntry)=>entry.quantity>0
const read=<T,>(key:string,fallback:T):T=>{try{return JSON.parse(sessionStorage.getItem(key)??'') as T}catch{return fallback}}
type ViewState={selectedSet:string;filter:'all'|'owned'|'missing'|'grading';search:string;sort:CardSort;expandedFamily:string|null;language:string;setPickerOpen:boolean}
const initial:ViewState={selectedSet:'30th',filter:'all',search:'',sort:'number',expandedFamily:null,language:'fr',setPickerOpen:false}
const cardmarketSearch=(card:SetCard,setName:string)=>`https://www.cardmarket.com/fr/Pokemon/Products/Search?searchString=${encodeURIComponent(`${card.name} ${setName} ${card.localId}`)}`
type Props={document:CollectionDocument;onChange:(document:CollectionDocument)=>void;isFavorite?:(card:Pick<FavoriteCard,'source'|'cardId'|'language'|'setId'>)=>boolean;onFavorite?:(card:FavoriteInput)=>void}
export function Portfolio({document,onChange,isFavorite=()=>false,onFavorite}:Props){
 const saved=useRef(read(VIEW_KEY,initial)).current
 const [filter,setFilter]=useState(saved.filter),[series,setSeries]=useState<SeriesSummary[]>([]),[expandedFamily,setExpandedFamily]=useState<string|null>(saved.expandedFamily),[familySets,setFamilySets]=useState<Record<string,SetSummary[]>>({}),[familyError,setFamilyError]=useState(''),[sets,setSets]=useState<SetSummary[]>([]),[selectedSet,setSelectedSet]=useState(saved.selectedSet),[detail,setDetail]=useState<SetDetail>(),[catalogueError,setCatalogueError]=useState(''),[search,setSearch]=useState(saved.search),[seriesQuery,setSeriesQuery]=useState(''),[setPickerOpen,setSetPickerOpen]=useState(saved.setPickerOpen),[editing,setEditing]=useState<SetCard|null>(null),[details,setDetails]=useState<SetCard|null>(null),[showcase,setShowcase]=useState<SetCard|null>(null),[quantityFlash,setQuantityFlash]=useState<string|null>(null),[sort,setSort]=useState<CardSort>(saved.sort),[language,setLanguage]=useState(saved.language),[recents,setRecents]=useState<string[]>(()=>read(RECENT_KEY,[])),[comparing,setComparing]=useState(false)
 const documentRef=useRef(document);documentRef.current=document
 const keyFor=useCallback((card:SetCard)=>printingKey({source:'tcgdex',setId:card.id.slice(0,card.id.lastIndexOf('-')),cardId:card.id,language,variant:'normal'}),[language])
 useEffect(()=>{let active=true;listSeries().then(x=>active&&setSeries(x.reverse())).catch(e=>active&&setFamilyError((e as Error).message));listSets(language).then(x=>active&&setSets(x)).catch(e=>active&&setCatalogueError((e as Error).message));return()=>{active=false}},[language])
 useEffect(()=>{let active=true;setDetail(undefined);getSet(selectedSet,language).then(x=>{if(active){setDetail(x);setCatalogueError('')}}).catch(e=>active&&setCatalogueError((e as Error).message));return()=>{active=false}},[selectedSet,language])
 useEffect(()=>{if(!expandedFamily||familySets[expandedFamily])return;let active=true;getSeries(expandedFamily).then(x=>active&&setFamilySets(c=>({...c,[x.id]:x.sets}))).catch(e=>active&&setFamilyError((e as Error).message));return()=>{active=false}},[expandedFamily,familySets])
 useEffect(()=>{sessionStorage.setItem(VIEW_KEY,JSON.stringify({selectedSet,filter,search,sort,expandedFamily,language,setPickerOpen}))},[selectedSet,filter,search,sort,expandedFamily,language,setPickerOpen])
 useEffect(()=>{if(detail?.serie?.id)setExpandedFamily(current=>current??detail.serie!.id)},[detail?.serie?.id])
 useEffect(()=>{const pop=()=>{setDetails(null);setComparing(false);setShowcase(null)};addEventListener('popstate',pop);return()=>removeEventListener('popstate',pop)},[])
 const entriesById=useMemo(()=>new Map(document.entries.filter(e=>e.language===language&&e.quantity>0).map(e=>[e.cardId,e])),[document,language]),ownedEntries=document.entries.filter(isOwned),setEntries=ownedEntries.filter(e=>e.setId===selectedSet&&e.language===language),priceIds=[...new Set([...ownedEntries.filter(e=>e.language===language).map(e=>e.cardId),...(detail?.cards.map(c=>c.id)??[])])],prices=useCardPrices(priceIds,language)
 const shown=useMemo(()=>sortCatalogueCards((detail?.cards??[]).filter(card=>(filter==='all'||(filter==='owned'?entriesById.has(card.id):filter==='missing'?!entriesById.has(card.id):getGradingInterest({rawPrice:prices[card.id]?.price?.value,rarity:card.rarity,...prices[card.id]?.cardmarket}).level==='high'))&&normalizeSearch(`${card.name} ${card.localId}`).includes(normalizeSearch(search))),sort,prices,entriesById),[detail,filter,entriesById,search,sort,prices])
 const summarize=(entries:CollectionEntry[])=>entries.reduce((r,e)=>{const unit=e.manualPrice??(e.language===language?prices[e.cardId]?.price?.value:undefined);if(unit===undefined)r.missing++;else{r.value+=unit*e.quantity;r.valued++}return r},{value:0,valued:0,missing:0}),globalSummary=summarize(ownedEntries.filter(e=>e.language===language)),setSummary=summarize(setEntries)
 const setEntry=(card:SetCard,change:Partial<CollectionEntry>={})=>{const previous=documentRef.current.entries.find(e=>e.key===keyFor(card));const next=upsertEntry(documentRef.current,{source:'tcgdex',setId:selectedSet,cardId:card.id,language,variant:'normal',name:card.name,setName:detail?.name??selectedSet,number:card.localId,image:card.image,rarity:card.rarity??previous?.rarity,quantity:previous?.quantity??1,condition:previous?.condition??'near-mint',notes:previous?.notes??'',manualPrice:previous?.manualPrice,...change});documentRef.current=next;onChange(next)}
 const favoriteFor=(card:SetCard):FavoriteInput=>({source:'tcgdex',setId:selectedSet,cardId:card.id,language,name:card.name,setName:detail?.name??selectedSet,localId:card.localId,image:card.image})
 const chooseSet=(id:string)=>{setSelectedSet(id);setSetPickerOpen(false);setSeriesQuery('');const parent=Object.entries(familySets).find(([,items])=>items.some(x=>x.id===id))?.[0];if(parent)setExpandedFamily(parent);const next=[id,...recents.filter(x=>x!==id)].slice(0,5);setRecents(next);localStorage.setItem(RECENT_KEY,JSON.stringify(next))}
 const openSubView=(kind:'card'|'comparison',card?:SetCard)=>{history.pushState({pokevalueSubView:kind},'');if(kind==='card'&&card)setDetails(card);else setComparing(true)}
 const closeSubView=()=>{if(history.state?.pokevalueSubView)history.back();else{setDetails(null);setComparing(false);setShowcase(null)}}
 const query=normalizeSearch(seriesQuery),results=query?sets.filter(s=>normalizeSearch(`${s.name} ${s.id} ${series.find(f=>familySets[f.id]?.some(x=>x.id===s.id))?.name??''}`).includes(query)).slice(0,30):[]
 return <section className="portfolio-page"><div className="portfolio-heading"><div><span className="eyebrow">Catalogue et classeur numérique</span><h1>Collection</h1><p>Moins de clics, sans perdre ta position.</p></div><div className="language-tabs" aria-label="Langue">{languages.map(([id,label])=><button className={language===id?'active':''} onClick={()=>setLanguage(id)} key={id}>{label}</button>)}</div></div>
 <div className="language-counts">{languages.map(([id,label])=><span key={id}>Collection {label} <b>{ownedEntries.filter(e=>e.language===id).length}</b></span>)}</div><div className="collection-summary"><div><small>Ma collection · {language.toUpperCase()}</small><strong>{ownedEntries.filter(e=>e.language===language).length} cartes différentes</strong><span>{ownedEntries.filter(e=>e.language===language).reduce((s,e)=>s+e.quantity,0)} exemplaires</span></div><div><small>Valeur estimée · EUR</small><strong>{globalSummary.missing?'≈ ':''}{money(globalSummary.value)}</strong><span>{globalSummary.valued} valorisées · {globalSummary.missing} sans prix</span></div><div><small>Extension actuelle</small><strong>{detail?.name??'Chargement…'}</strong><span>{money(setSummary.value)} · {setEntries.length}/{detail?.cardCount.total??'…'} possédées</span></div></div>
 <div className="series-selector"><div><span className="eyebrow">Explorer les extensions</span><h2>{detail?.name??'Choisir une série'}</h2><p>{detail?.serie?.name??`Catalogue ${language.toUpperCase()}`}</p></div><button className="series-picker-trigger" aria-expanded={setPickerOpen} aria-controls="series-picker-list" onClick={()=>setSetPickerOpen(x=>!x)}>Changer de série <ChevronDown size={18}/></button>
 {setPickerOpen&&<div className="series-picker" id="series-picker-list"><div className="series-search-sticky"><input className="series-search" placeholder="Rechercher une série ou extension…" value={seriesQuery} onChange={e=>setSeriesQuery(e.target.value)}/></div>{!query&&recents.length>0&&<div className="recent-sets"><small>Récemment consultées</small>{recents.map(id=>sets.find(s=>s.id===id)).filter((x):x is SetSummary=>!!x).map(s=><button key={s.id} onClick={()=>chooseSet(s.id)}>{s.name}</button>)}</div>}{query?<div className="series-picker-list global-set-results">{results.map(set=><button key={set.id} onClick={()=>chooseSet(set.id)}><span>{set.name}<small>{series.find(f=>familySets[f.id]?.some(x=>x.id===set.id))?.name??set.id}</small></span></button>)}</div>:<div className="series-families">{series.map(family=><div className="series-family" key={family.id}><button className="series-family-trigger" aria-expanded={expandedFamily===family.id} aria-controls={`family-${family.id}`} onClick={()=>setExpandedFamily(x=>x===family.id?null:family.id)}>{family.name}<ChevronDown size={16}/></button>{expandedFamily===family.id&&<div className="series-family-content" id={`family-${family.id}`}>{!familySets[family.id]?<p>Chargement…</p>:familySets[family.id].map(set=><button key={set.id} className={selectedSet===set.id?'selected':''} aria-current={selectedSet===set.id?'true':undefined} onClick={()=>chooseSet(set.id)}>{set.name}<small>{document.entries.filter(e=>isOwned(e)&&e.setId===set.id).length}/{set.cardCount.total}</small></button>)}</div>}</div>)}</div>}{familyError&&<p role="alert">{familyError}</p>}</div>}</div>
 <div className="series-controls"><button onClick={()=>openSubView('comparison')}>Comparer les séries</button><input placeholder="Nom ou numéro dans cette série" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Trier les cartes" value={sort} onChange={e=>setSort(e.target.value as CardSort)}><option value="number">Numéro de carte</option><option value="name-asc">Nom A → Z</option><option value="name-desc">Nom Z → A</option><option value="price-asc">Prix croissant</option><option value="price-desc">Prix décroissant</option><option value="owned">Possédées en premier</option><option value="quantity">Quantité décroissante</option><option value="grading">Potentiel gradation</option></select>{(['all','owned','missing','grading'] as const).map(f=><button className={filter===f?'active':''} onClick={()=>setFilter(f)} key={f}>{f==='all'?'Toutes':f==='owned'?'Possédées':f==='missing'?'Manquantes':'Potentiel élevé'}</button>)}</div>
 {catalogueError&&<p role="alert">{catalogueError}</p>}<div className="binder-grid">{shown.map(card=>{const entry=entriesById.get(card.id),has=!!entry,favorite=isFavorite(favoriteFor(card));return <article key={card.id} className={has?'owned':''}><button className="binder-preview" onClick={()=>setShowcase(card)} aria-label={`Voir ${card.name} en 3D`}><CatalogueImage card={card} requestedLanguage={language}/></button>{getGradingInterest({rawPrice:prices[card.id]?.price?.value,rarity:card.rarity,...prices[card.id]?.cardmarket}).level==='high'&&<span className="tile-grading-badge" title="Potentiel à étudier — estimation basée sur prix, rareté et tendance">★ Potentiel gradation</span>}<strong>{card.name}</strong><span>{card.localId}/{detail?.cardCount.official??detail?.cardCount.total} · {detail?.name}</span><div className="binder-price"><small>Prix marché · {language.toUpperCase()}</small>{prices[card.id]?.price?<strong>{money(prices[card.id].price!.value)}</strong>:<span>Prix indisponible</span>}</div><div className="card-quick-actions"><span>{has?`✓ ×${entry.quantity}`:'Non possédée'}</span>{has?<button className={quantityFlash===card.id?'quantity-flash':''} onClick={()=>{setEntry(card,{quantity:entry.quantity+1});setQuantityFlash(card.id);setTimeout(()=>setQuantityFlash(null),450)}} aria-label={`Ajouter un exemplaire de ${card.name}`}><Plus size={15}/>1</button>:<button onClick={()=>setEditing(card)}>Ajouter</button>}{onFavorite&&<FavoriteButton favorite={favorite} onToggle={()=>onFavorite(favoriteFor(card))}/>}<button onClick={()=>openSubView('card',card)} aria-label={`Détails et statistiques de ${card.name}`}><BarChart3 size={17}/></button></div></article>})}</div>
 {comparing&&<SeriesComparison sets={sets} currentSet={selectedSet} entries={ownedEntries} prices={prices} language={language} onClose={closeSubView}/>} {details&&<CardDetailsModal card={details} setName={detail?.name??selectedSet} language={language} entry={entriesById.get(details.id)} price={prices[details.id]} favorite={isFavorite(favoriteFor(details))} onFavorite={onFavorite?()=>onFavorite(favoriteFor(details)):undefined} onQuantity={quantity=>setEntry(details,{quantity})} onEdit={()=>{setDetails(null);setEditing(details)}} onShowcase={()=>{setShowcase(details);setDetails(null)}} onClose={closeSubView}/>} {showcase&&<CardShowcase card={showcase} setName={detail?.name??selectedSet} owned={entriesById.has(showcase.id)} quantity={entriesById.get(showcase.id)?.quantity} onToggle={()=>setEntry(showcase,{quantity:1})} onIncrement={()=>setEntry(showcase,{quantity:(entriesById.get(showcase.id)?.quantity??0)+1})} favorite={isFavorite(favoriteFor(showcase))} onFavorite={onFavorite?()=>onFavorite(favoriteFor(showcase)):undefined} onDetails={()=>{setShowcase(null);openSubView('card',showcase)}} onClose={()=>setShowcase(null)} cardmarketUrl={cardmarketSearch(showcase,detail?.name??selectedSet)}/>} {editing&&<CardEditor key={editing.id} card={editing} setName={detail?.name??selectedSet} entry={entriesById.get(editing.id)} automaticPrice={prices[editing.id]?.price} onSave={draft=>{setEntry(editing,draft);setEditing(null)}} onRemove={()=>{setEntry(editing,{quantity:0});setEditing(null)}} onClose={()=>setEditing(null)}/>}</section>
}
