import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { BarChart3, ChevronDown, Minus, Plus } from 'lucide-react'
import { listSets,getSet,listSeries,getSeries,type CatalogLanguage,type SeriesSummary,type SetDetail,type SetSummary,type SetCard } from '../api/sets'
import { CatalogueImage } from './CatalogueImage'
import type { CollectionDocument,CollectionEntry } from '../domain/collection'
import { collectionUnitPrice,printingKey,upsertEntry } from '../domain/collection'
import { CardEditor } from './CardEditor'
import { CardDetailsModal } from './CardDetailsModal'
import { SeriesComparison } from './SeriesComparison'
import {CardShowcase} from './CardShowcase'
import { useCardPrices } from '../hooks/useCardPrices'
import { money } from '../utils/money'
import { normalizeSearch,sortCatalogueCards,type CardSort } from '../domain/catalogue'
import {getGradingInterest} from '../domain/grading'
import type {FavoriteCard,FavoriteInput} from '../domain/favorites'
import {FavoriteButton} from './FavoriteButton'
import { CollectionExport } from './CollectionExport'

const VIEW_KEY='pv-collection-view-v1',RECENT_KEY='pv-recent-sets-v1',COLUMNS_KEY='pv-collection-columns'
const languages=[['fr','FR'],['en','EN'],['ja','JP'],['zh-tw','ZH']] as const
const isOwned=(entry:CollectionEntry)=>entry.quantity>0
const read=<T,>(key:string,fallback:T):T=>{try{return JSON.parse(sessionStorage.getItem(key)??'') as T}catch{return fallback}}
type ViewState={selectedSet:string;filter:'all'|'owned'|'missing'|'grading';search:string;sort:CardSort;expandedFamily:string|null;language:CatalogLanguage;setPickerOpen:boolean}
type CollectionDisplay='cards'|'list'|'grid'
const initial:ViewState={selectedSet:'30th',filter:'all',search:'',sort:'number',expandedFamily:null,language:'fr',setPickerOpen:false}
export const maxCollectionColumns=(width:number)=>width>=1200?5:width>=900?4:width>=640?3:width>=340?2:1
export const effectiveCollectionColumns=(preferred:number,width:number)=>Math.min(Math.max(1,Math.min(5,preferred)),maxCollectionColumns(width))
const displaySetName=(name?:string)=>name?.replace(/Collection Classique\s*30[ᵉe]?\s*Anniversaire/i,'Collection Classique · 30e Anniversaire')
const setLogoSources=(setId:string,seriesId?:string,logo?:string,symbol?:string)=>{
 const english=(url?:string)=>url?.replace('/fr/','/en/').replace('/ja/','/en/').replace('/zh-tw/','/en/')
 const base=seriesId?'https://assets.tcgdex.net/en/'+seriesId+'/'+setId:''
 return [...new Set([logo,english(logo),base?base+'/logo':undefined,symbol,english(symbol),base?base+'/symbol':undefined].filter((url):url is string=>!!url))]
}
type Props={document:CollectionDocument;onChange:(document:CollectionDocument)=>void;isFavorite?:(card:Pick<FavoriteCard,'source'|'cardId'|'language'|'setId'>)=>boolean;onFavorite?:(card:FavoriteInput)=>void}
type CollectionQuantityStepperProps={entry?:CollectionEntry;cardName:string;flash:boolean;onDecrement:()=>void;onIncrement:()=>void}
export function CollectionQuantityStepper({entry,cardName,flash,onDecrement,onIncrement}:CollectionQuantityStepperProps){
 if(!entry)return null
 return <div className="collection-quantity" aria-label="Gérer la quantité">
  <button onClick={onDecrement} aria-label={`Retirer un exemplaire de ${cardName}`} title="Retirer un exemplaire"><Minus size={16}/></button>
  <span aria-live="polite" aria-label={`${entry.quantity} exemplaire${entry.quantity===1?'':'s'}`}>×{entry.quantity}</span>
  <button className={flash?'quantity-flash':''} onClick={onIncrement} aria-label={`Ajouter un exemplaire de ${cardName}`} title="Ajouter un exemplaire"><Plus size={16}/></button>
 </div>
}
type SetBadgeProps={sources:string[];name:string;imageClass:string;fallbackClass:string}
function SetBadge({sources,name,imageClass,fallbackClass}:SetBadgeProps){
 const [index,setIndex]=useState(0)
 const sourceKey=sources.join('|')
 useEffect(()=>setIndex(0),[sourceKey])
 const mark=name.match(/30|[A-ZÀ-Þ]{2}/i)?.[0]??name.trim().split(/\s+/).slice(0,2).map(word=>word[0]).join('').toUpperCase()
 const src=sources[index]
 return src?<img className={imageClass} src={src} alt={'Logo '+name} loading='lazy' onError={()=>setIndex(current=>Math.min(current+1,sources.length))}/>:<span className={fallbackClass} aria-label={'Repère '+name}>{mark}</span>
}
export function Portfolio({document,onChange,isFavorite=()=>false,onFavorite}:Props){
 const saved=useRef(read(VIEW_KEY,initial)).current
 const gridRef=useRef<HTMLDivElement>(null)
 const [preferredColumns,setPreferredColumns]=useState(()=>{const value=Number(localStorage.getItem(COLUMNS_KEY));return value>=1&&value<=5?value:5}),[maxColumns,setMaxColumns]=useState(5)
 const [filter,setFilter]=useState(saved.filter),[series,setSeries]=useState<SeriesSummary[]>([]),[expandedFamily,setExpandedFamily]=useState<string|null>(saved.expandedFamily),[familySets,setFamilySets]=useState<Record<string,SetSummary[]>>({}),[familyError,setFamilyError]=useState(''),[sets,setSets]=useState<SetSummary[]>([]),[selectedSet,setSelectedSet]=useState(saved.selectedSet),[detail,setDetail]=useState<SetDetail>(),[catalogueError,setCatalogueError]=useState(''),[search,setSearch]=useState(saved.search),[seriesQuery,setSeriesQuery]=useState(''),[setPickerOpen,setSetPickerOpen]=useState(saved.setPickerOpen),[editing,setEditing]=useState<SetCard|null>(null),[details,setDetails]=useState<SetCard|null>(null),[showcase,setShowcase]=useState<SetCard|null>(null),[quantityFlash,setQuantityFlash]=useState<string|null>(null),[sort,setSort]=useState<CardSort>(saved.sort),[language,setLanguage]=useState(saved.language),[recents,setRecents]=useState<string[]>(()=>read(RECENT_KEY,[])),[comparing,setComparing]=useState(false),[displayMode,setDisplayMode]=useState<CollectionDisplay>(()=>{try{const value=JSON.parse(localStorage.getItem('pv-collection-display-v1')??'"cards"');return value==='list'||value==='grid'||value==='cards'?value:'cards'}catch{return'cards'}})
 const documentRef=useRef(document);documentRef.current=document
 const keyFor=useCallback((card:SetCard)=>printingKey({source:'tcgdex',setId:card.id.slice(0,card.id.lastIndexOf('-')),cardId:card.id,language,variant:'normal'}),[language])
 useEffect(()=>{let active=true;setFamilySets({});setFamilyError('');listSeries(language).then(x=>active&&setSeries(x.reverse())).catch(e=>active&&setFamilyError((e as Error).message));listSets(language).then(x=>{if(!active)return;setSets(x);if(!x.some(set=>set.id===selectedSet))setSelectedSet(x[x.length-1]?.id??'')}).catch(e=>active&&setCatalogueError((e as Error).message));return()=>{active=false}},[language])
 useEffect(()=>{let active=true;setDetail(undefined);getSet(selectedSet,language).then(x=>{if(active){setDetail(x);setCatalogueError('')}}).catch(e=>active&&setCatalogueError((e as Error).message));return()=>{active=false}},[selectedSet,language])
 useEffect(()=>{if(!expandedFamily||familySets[expandedFamily])return;let active=true;getSeries(expandedFamily,language).then(x=>active&&setFamilySets(c=>({...c,[x.id]:x.sets}))).catch(e=>active&&setFamilyError((e as Error).message));return()=>{active=false}},[expandedFamily,familySets,language])
 useEffect(()=>{sessionStorage.setItem(VIEW_KEY,JSON.stringify({selectedSet,filter,search,sort,expandedFamily,language,setPickerOpen}))},[selectedSet,filter,search,sort,expandedFamily,language,setPickerOpen])
 useEffect(()=>{localStorage.setItem('pv-collection-display-v1',JSON.stringify(displayMode))},[displayMode])
 useEffect(()=>{if(detail?.serie?.id)setExpandedFamily(current=>current??detail.serie!.id)},[detail?.serie?.id])
 useEffect(()=>{const pop=()=>{setDetails(null);setComparing(false);setShowcase(null)};addEventListener('popstate',pop);return()=>removeEventListener('popstate',pop)},[])
 useEffect(()=>{const node=gridRef.current;if(!node)return;const update=()=>setMaxColumns(maxCollectionColumns(node.getBoundingClientRect().width));update();const observer=new ResizeObserver(update);observer.observe(node);return()=>observer.disconnect()},[])
 useEffect(()=>{localStorage.setItem(COLUMNS_KEY,String(preferredColumns))},[preferredColumns])
 const entriesById=useMemo(()=>new Map(document.entries.filter(e=>e.language===language&&e.quantity>0).map(e=>[e.cardId,e])),[document,language]),ownedEntries=document.entries.filter(isOwned),setEntries=ownedEntries.filter(e=>e.setId===selectedSet&&e.language===language),priceIds=[...new Set([...ownedEntries.filter(e=>e.language===language).map(e=>e.cardId),...(detail?.cards.map(c=>c.id)??[])])],prices=useCardPrices(priceIds,language)
 const shown=useMemo(()=>sortCatalogueCards((detail?.cards??[]).filter(card=>(filter==='all'||(filter==='owned'?entriesById.has(card.id):filter==='missing'?!entriesById.has(card.id):getGradingInterest({rawPrice:prices[card.id]?.price?.value,rarity:card.rarity,...prices[card.id]?.cardmarket}).level==='high'))&&normalizeSearch(`${card.name} ${card.localId}`).includes(normalizeSearch(search))),sort,prices,entriesById),[detail,filter,entriesById,search,sort,prices])
 const raritySummary=useMemo(()=>{const groups=new Map<string,{total:number;owned:number}>();for(const card of detail?.cards??[]){const rarity=card.rarity||'Rareté non précisée',group=groups.get(rarity)??{total:0,owned:0};group.total++;if(entriesById.has(card.id))group.owned++;groups.set(rarity,group)}return [...groups.entries()].sort((a,b)=>b[1].total-a[1].total).slice(0,8)},[detail,entriesById])
 const setOwnedCount=(detail?.cards??[]).reduce((count,card)=>count+(entriesById.has(card.id)?1:0),0),setTotal=detail?.cardCount.total??0,setProgress=setTotal?Math.min(100,Math.round(setOwnedCount/setTotal*100)):0
 const summarize=(entries:CollectionEntry[])=>entries.reduce((r,e)=>{const unit=collectionUnitPrice(e,e.language===language?prices[e.cardId]?.price?.value:undefined);if(unit===undefined)r.missing++;else{r.value+=unit*e.quantity;r.valued++}return r},{value:0,valued:0,missing:0}),globalSummary=summarize(ownedEntries.filter(e=>e.language===language)),setSummary=summarize(setEntries)
 const setEntry=(card:SetCard,change:Partial<CollectionEntry>={})=>{const previous=documentRef.current.entries.find(e=>e.key===keyFor(card));const next=upsertEntry(documentRef.current,{source:'tcgdex',setId:selectedSet,cardId:card.id,language,variant:'normal',name:card.name,setName:detail?.name??selectedSet,number:card.localId,image:card.image,rarity:card.rarity??previous?.rarity,quantity:previous?.quantity&&previous.quantity>0?previous.quantity:1,condition:previous?.condition??'near-mint',notes:previous?.notes??'',manualPrice:previous?.manualPrice,priceMode:previous?.priceMode,...change});documentRef.current=next;onChange(next)}
 const favoriteFor=(card:SetCard):FavoriteInput=>({source:'tcgdex',setId:selectedSet,cardId:card.id,language,name:card.name,setName:detail?.name??selectedSet,localId:card.localId,image:card.image})
 const chooseSet=(id:string)=>{setSelectedSet(id);setSetPickerOpen(false);setSeriesQuery('');const parent=Object.entries(familySets).find(([,items])=>items.some(x=>x.id===id))?.[0];if(parent)setExpandedFamily(parent);const next=[id,...recents.filter(x=>x!==id)].slice(0,5);setRecents(next);localStorage.setItem(RECENT_KEY,JSON.stringify(next))}
 const openSubView=(kind:'card'|'comparison',card?:SetCard)=>{history.pushState({pokevalueSubView:kind},'');if(kind==='card'&&card)setDetails(card);else setComparing(true)}
 const closeSubView=()=>{if(history.state?.pokevalueSubView)history.back();else{setDetails(null);setComparing(false);setShowcase(null)}}
 const query=normalizeSearch(seriesQuery),results=query?sets.filter(s=>normalizeSearch(`${s.name} ${s.id} ${series.find(f=>familySets[f.id]?.some(x=>x.id===s.id))?.name??''}`).includes(query)).slice(0,30):[]
 return <section className="portfolio-page"><div className="portfolio-heading"><div><span className="eyebrow">Catalogue et classeur numérique</span><h1>Collection</h1><p>Moins de clics, sans perdre ta position.</p></div><div className="language-tabs" aria-label="Langue">{languages.map(([id,label])=><button className={language===id?'active':''} onClick={()=>setLanguage(id)} key={id}>{label}</button>)}</div></div>
 <div className="language-counts">{languages.map(([id,label])=><span key={id}>Collection {label} <b>{ownedEntries.filter(e=>e.language===id).length}</b></span>)}</div><div className="collection-summary"><div><small>Ma collection · {language.toUpperCase()}</small><strong>{ownedEntries.filter(e=>e.language===language).length} cartes différentes</strong><span>{ownedEntries.filter(e=>e.language===language).reduce((s,e)=>s+e.quantity,0)} exemplaires</span></div><div><small>Valeur estimée · EUR</small><strong>{globalSummary.missing?'≈ ':''}{money(globalSummary.value)}</strong><span>{globalSummary.valued} valorisées · {globalSummary.missing} sans prix</span></div><div><small>Extension actuelle</small><strong>{displaySetName(detail?.name)??'Chargement…'}</strong><span>{money(setSummary.value)} · {setEntries.length}/{detail?.cardCount.total??'…'} possédées</span></div></div>
 <CollectionExport entries={ownedEntries}/>
 <div className="series-selector"><div><span className="eyebrow">Explorer les extensions</span><h2>{displaySetName(detail?.name)??'Choisir une série'}</h2><p>{detail?.serie?.name??`Catalogue ${language.toUpperCase()}`}</p></div><button className="series-picker-trigger" aria-expanded={setPickerOpen} aria-controls="series-picker-list" onClick={()=>setSetPickerOpen(x=>!x)}>Changer de série <ChevronDown size={18}/></button>
 {setPickerOpen&&<div className="series-picker" id="series-picker-list"><div className="series-search-sticky"><input className="series-search" placeholder="Rechercher une série ou extension…" value={seriesQuery} onChange={e=>setSeriesQuery(e.target.value)}/></div>{!query&&recents.length>0&&<div className="recent-sets"><small>Récemment consultées</small>{recents.map(id=>sets.find(s=>s.id===id)).filter((x):x is SetSummary=>!!x).map(s=><button key={s.id} onClick={()=>chooseSet(s.id)}>{s.name}</button>)}</div>}{query?<div className="series-picker-list global-set-results">{results.map(set=><button key={set.id} onClick={()=>chooseSet(set.id)}><span>{set.name}<small>{series.find(f=>familySets[f.id]?.some(x=>x.id===set.id))?.name??set.id}</small></span></button>)}</div>:<div className="series-families">{series.map(family=><div className="series-family" key={family.id}><button className="series-family-trigger" aria-expanded={expandedFamily===family.id} aria-controls={`family-${family.id}`} onClick={()=>setExpandedFamily(x=>x===family.id?null:family.id)}><SetBadge sources={setLogoSources(familySets[family.id]?.[0]?.id??"",family.id,familySets[family.id]?.[0]?.logo,familySets[family.id]?.[0]?.symbol)} name={family.name} imageClass="series-family-logo" fallbackClass="series-family-monogram"/><span>{family.name}</span><ChevronDown size={16}/></button>{expandedFamily===family.id&&<div className="series-family-content" id={`family-${family.id}`}>{!familySets[family.id]?<p>Chargement…</p>:familySets[family.id].map(set=>{const ownedCount=new Set(document.entries.filter(e=>isOwned(e)&&e.setId===set.id&&e.language===language).map(e=>e.cardId)).size;const total=set.cardCount.total;const progress=total?Math.min(100,Math.round(ownedCount/total*100)):0;return <button key={set.id} className={`series-progress-row${selectedSet===set.id?' selected':''}${progress===100?' complete':''}`} aria-current={selectedSet===set.id?'true':undefined} aria-label={`${set.name} : ${ownedCount} sur ${total} cartes, ${progress} % complété`} onClick={()=>chooseSet(set.id)}><span className="series-progress-heading"><SetBadge sources={setLogoSources(set.id,family.id,set.logo,set.symbol)} name={set.name} imageClass="series-progress-logo" fallbackClass="series-progress-monogram"/><span className="series-progress-name">{set.name}</span><span className="series-progress-count"><strong>{ownedCount}</strong><span>/{total}</span></span><span className="series-progress-percent">{progress}%</span></span><span className="series-progress-track" aria-hidden="true"><span style={{width:`${progress}%`}}/></span></button>})}</div>}</div>)}</div>}{familyError&&<p role="alert">{familyError}</p>}</div>}</div>
 <section className="set-overview" aria-label="Résumé de l’extension"><div className="set-overview-main"><SetBadge sources={setLogoSources(detail?.id??selectedSet,detail?.serie?.id,detail?.logo??sets.find(set=>set.id===selectedSet)?.logo,detail?.symbol??sets.find(set=>set.id===selectedSet)?.symbol)} name={detail?.name??selectedSet} imageClass="set-overview-logo" fallbackClass="set-overview-monogram"/><div className="set-overview-info"><span className="eyebrow">{detail?.serie?.name??'Extension sélectionnée'}</span><h2>{displaySetName(detail?.name)??'Chargement du catalogue…'}</h2><p>{detail?.cardCount.official??'…'} cartes officielles · {language.toUpperCase()}</p></div><div className="set-overview-progress"><strong>{setOwnedCount}<span> / {setTotal}</span></strong><b>{setProgress}%</b><small>de l’extension complétée</small><div className="set-overview-track"><span style={{width:`${setProgress}%`}}/></div></div></div><div className="set-rarity-summary" aria-label="Progression par rareté">{raritySummary.map(([rarity,count])=><div className="rarity-stat" key={rarity} title={`${rarity} : ${count.owned} sur ${count.total}`}><span>{rarity}</span><strong>{count.owned}<small>/{count.total}</small></strong><span className="rarity-track"><i style={{width:`${count.total?count.owned/count.total*100:0}%`}}/></span></div>)}</div></section>
 <div className="collection-view-switch" role="group" aria-label="Mode d’affichage">{([['cards','Cartes'],['list','Liste'],['grid','Grille']] as const).map(([mode,label])=><button type="button" key={mode} className={displayMode===mode?'active':''} aria-pressed={displayMode===mode} onClick={()=>setDisplayMode(mode)}>{label}</button>)}</div>
 <div className={`series-controls${displayMode!=='cards'?' view-controls-compact':''}`}><label className="control-search"><span>Recherche</span><input placeholder="Nom ou numéro dans cette série" value={search} onChange={e=>setSearch(e.target.value)}/></label><label className="control-sort"><span>Tri</span><select aria-label="Trier les cartes" value={sort} onChange={e=>setSort(e.target.value as CardSort)}><option value="number">Numéro de carte</option><option value="name-asc">Nom A → Z</option><option value="name-desc">Nom Z → A</option><option value="price-asc">Prix croissant</option><option value="price-desc">Prix décroissant</option><option value="owned">Possédées en premier</option><option value="quantity">Quantité décroissante</option><option value="grading">Potentiel gradation</option></select></label>{displayMode==='cards'&&<label className="control-columns"><span>Cartes par ligne</span><select aria-label="Cartes par ligne" value={Math.min(preferredColumns,maxColumns)} onChange={e=>setPreferredColumns(Number(e.target.value))}>{Array.from({length:maxColumns},(_,index)=>index+1).map(value=><option key={value} value={value}>{value}</option>)}</select></label>}<div className="control-filters" aria-label="Filtres">{(['all','owned','missing','grading'] as const).map(f=><button className={filter===f?'active':''} onClick={()=>setFilter(f)} key={f}>{f==='all'?'Toutes':f==='owned'?'Possédées':f==='missing'?'Manquantes':'Gradation'}</button>)}</div><div className="control-actions"><button onClick={()=>openSubView('comparison')}>Comparer les séries</button></div></div><p className="catalogue-count">{shown.length} carte{shown.length===1?'':'s'} affichée{shown.length===1?'':'s'}</p>
 {catalogueError&&<p role="alert">{catalogueError}</p>}
 <div ref={gridRef} className={`binder-grid view-${displayMode}`} style={{'--collection-columns':displayMode==='list'?1:displayMode==='grid'?Math.min(5,maxColumns+1):Math.min(preferredColumns,maxColumns)} as React.CSSProperties}>
  {shown.map(card=>{
   const entry=entriesById.get(card.id),has=!!entry,favorite=isFavorite(favoriteFor(card))
   const changeQuantity=(quantity:number)=>setEntry(card,{quantity})
   const utilities=<div className="card-utility-actions">
    {onFavorite&&<FavoriteButton favorite={favorite} onToggle={()=>onFavorite(favoriteFor(card))}/>}
    <button onClick={()=>openSubView('card',card)} aria-label={`Détails et statistiques de ${card.name}`} title="Détails et statistiques"><BarChart3 size={17}/></button>
   </div>
   return <article key={card.id} className={has?'owned':''}>
    <button className="binder-preview" onClick={()=>setShowcase(card)} aria-label={`Voir ${card.name} en 3D`}><CatalogueImage card={card} requestedLanguage={language}/></button>
    {getGradingInterest({rawPrice:prices[card.id]?.price?.value,rarity:card.rarity,...prices[card.id]?.cardmarket}).level==='high'&&<span className="tile-grading-badge" title="Potentiel à étudier — estimation basée sur prix, rareté et tendance">★ Potentiel gradation</span>}
    <strong className="binder-title">{card.name}</strong>
    <span className="binder-meta">{card.localId}/{detail?.cardCount.official??detail?.cardCount.total} · {selectedSet==='30th-c'?'Classique 30e':displaySetName(detail?.name)}</span>
    <div className="binder-price"><small>Référence Cardmarket · langue non filtrée</small>{prices[card.id]?.price?<strong>{money(prices[card.id].price!.value)}</strong>:<span>Prix indisponible</span>}</div>
    <div className={`card-quick-actions ${has?'is-owned':'is-missing'}`}>
     {entry?<CollectionQuantityStepper entry={entry} cardName={card.name} flash={quantityFlash===card.id} onDecrement={()=>changeQuantity(Math.max(0,entry.quantity-1))} onIncrement={()=>{changeQuantity(entry.quantity+1);setQuantityFlash(card.id);setTimeout(()=>setQuantityFlash(null),450)}}/>:<button className="add-card-action" aria-label={`Ajouter ${card.name} à ma collection`} onClick={()=>setEditing(card)}><Plus size={15}/> <span>Ajouter à ma collection</span></button>}
     {utilities}
    </div>
   </article>
  })}
 </div>
 {comparing&&<SeriesComparison sets={sets} currentSet={selectedSet} entries={ownedEntries} prices={prices} language={language} onClose={closeSubView}/>} {details&&<CardDetailsModal card={details} setName={detail?.name??selectedSet} language={language} entry={entriesById.get(details.id)} price={prices[details.id]} favorite={isFavorite(favoriteFor(details))} onFavorite={onFavorite?()=>onFavorite(favoriteFor(details)):undefined} onQuantity={quantity=>setEntry(details,{quantity})} onEdit={()=>{setDetails(null);setEditing(details)}} onShowcase={()=>{setShowcase(details);setDetails(null)}} onClose={closeSubView}/>} {showcase&&<CardShowcase card={showcase} setName={detail?.name??selectedSet} owned={entriesById.has(showcase.id)} quantity={entriesById.get(showcase.id)?.quantity} onToggle={()=>setEntry(showcase,{quantity:1})} onIncrement={()=>setEntry(showcase,{quantity:(entriesById.get(showcase.id)?.quantity??0)+1})} onDecrement={()=>setEntry(showcase,{quantity:Math.max(0,(entriesById.get(showcase.id)?.quantity??0)-1)})} favorite={isFavorite(favoriteFor(showcase))} onFavorite={onFavorite?()=>onFavorite(favoriteFor(showcase)):undefined} onDetails={()=>{setShowcase(null);openSubView('card',showcase)}} onClose={()=>setShowcase(null)}/>} {editing&&<CardEditor key={editing.id} card={editing} setName={detail?.name??selectedSet} language={language} entry={entriesById.get(editing.id)} automaticPrice={prices[editing.id]?.price} onSave={draft=>{setEntry(editing,draft);setEditing(null)}} onRemove={()=>{setEntry(editing,{quantity:0});setEditing(null)}} onClose={()=>setEditing(null)}/>}</section>
}
