import { useEffect,useMemo,useState } from 'react'
import { X } from 'lucide-react'
import type { SetSummary } from '../api/sets'
import type { CollectionEntry } from '../domain/collection'
import type { CardPriceState } from '../hooks/useCardPrices'
import { money } from '../utils/money'
type Sort='value'|'progress'|'average'|'top'|'owned'
type Props={sets:SetSummary[];currentSet:string;entries:CollectionEntry[];prices:Record<string,CardPriceState>;language:string;onClose:()=>void}
export function SeriesComparison({sets,currentSet,entries,prices,language,onClose}:Props){
 const [selected,setSelected]=useState<string[]>([currentSet]),[sort,setSort]=useState<Sort>('value')
 useEffect(()=>{const y=scrollY,old=document.body.style.overflow;document.body.style.overflow='hidden';const key=(e:KeyboardEvent)=>e.key==='Escape'&&onClose();addEventListener('keydown',key);return()=>{document.body.style.overflow=old;scrollTo(0,y);removeEventListener('keydown',key)}},[onClose])
 const rows=useMemo(()=>selected.map(id=>{const set=sets.find(x=>x.id===id),owned=entries.filter(e=>e.setId===id&&e.language===language&&e.quantity>0),values=owned.map(e=>({entry:e,value:(e.manualPrice??prices[e.cardId]?.price?.value)})).filter(x=>x.value!==undefined) as {entry:CollectionEntry;value:number}[],value=values.reduce((n,x)=>n+x.value*x.entry.quantity,0),top=values.sort((a,b)=>b.value-a.value)[0];return{id,name:set?.name??id,total:set?.cardCount.total??0,owned:owned.length,progress:set?.cardCount.total?owned.length/set.cardCount.total*100:0,value,average:owned.length?value/owned.length:0,top}}).sort((a,b)=>sort==='progress'?b.progress-a.progress:sort==='average'?b.average-a.average:sort==='top'?(b.top?.value??0)-(a.top?.value??0):sort==='owned'?b.owned-a.owned:b.value-a.value),[selected,sets,entries,language,prices,sort])
 return <div className="details-backdrop"><section className="series-comparison card-details" role="dialog" aria-modal="true" aria-labelledby="comparison-title"><button className="details-close" onClick={onClose} aria-label="Fermer la comparaison"><X/></button><span className="eyebrow">Analyse progressive</span><h2 id="comparison-title">Comparer les séries</h2><p>Sélectionne de 2 à 4 extensions. Seules les cartes de ta collection et leurs prix déjà chargés sont utilisées.</p><div className="comparison-picker">{sets.map(set=><label key={set.id}><input type="checkbox" checked={selected.includes(set.id)} disabled={!selected.includes(set.id)&&selected.length>=4} onChange={()=>setSelected(x=>x.includes(set.id)?x.filter(id=>id!==set.id):[...x,set.id])}/>{set.name}</label>)}</div><label className="comparison-sort">Trier par <select value={sort} onChange={e=>setSort(e.target.value as Sort)}><option value="value">Valeur collection</option><option value="progress">Progression</option><option value="average">Prix moyen</option><option value="top">Carte la plus chère</option><option value="owned">Cartes possédées</option></select></label><div className="comparison-grid">{rows.map(row=><article key={row.id}><h3>{row.name}</h3><strong>{row.owned} / {row.total} cartes</strong><span>{row.progress.toFixed(1)} %</span><span>Valeur : {money(row.value)}</span><span>Moyenne : {money(row.average)}</span><span>Top : {row.top?`${row.top.entry.name} · ${money(row.top.value)}`:'indisponible'}</span></article>)}</div></section></div>
}
