import type { Card } from './types'

export const cards: Card[] = [
  { id:'charizard-base', tcgdexId:'base1-4', name:'Dracaufeu Holo', pokemon:'Dracaufeu', set:'Set de Base', year:1999, number:'4/102', rarity:'Holo rare', language:'FR', rawMin:180, rawMax:900, graded10:12000, trend:'up', score:10, featured:true, color:'#f97316', accent:'#7c2d12', note:'Icône historique. La valeur dépend énormément de l’édition, de l’état et de l’absence de pli.' },
  { id:'umbreon-vmax', tcgdexId:'swsh7-215', name:'Noctali VMAX Alt Art', pokemon:'Noctali', set:'Évolution Céleste', year:2021, number:'215/203', rarity:'Secrète alternative', language:'FR', rawMin:750, rawMax:1250, graded10:2200, trend:'up', score:10, featured:true, color:'#312e81', accent:'#a78bfa', note:'Une des cartes modernes les plus recherchées de l’ère Épée & Bouclier.' },
  { id:'giratina-v', name:'Giratina V Alt Art', pokemon:'Giratina', set:'Origine Perdue', year:2022, number:'186/196', rarity:'Alternative', language:'FR', rawMin:260, rawMax:430, graded10:750, trend:'up', score:9.7, featured:true, color:'#4c1d95', accent:'#f59e0b', note:'Illustration très distinctive et forte demande collectionneur.' },
  { id:'rayquaza-vmax', name:'Rayquaza VMAX Alt Art', pokemon:'Rayquaza', set:'Évolution Céleste', year:2021, number:'218/203', rarity:'Secrète alternative', language:'FR', rawMin:330, rawMax:600, graded10:1050, trend:'up', score:9.6, featured:true, color:'#065f46', accent:'#facc15', note:'Carte moderne premium avec une forte liquidité.' },
  { id:'gengar-vmax', name:'Ectoplasma VMAX Alt Art', pokemon:'Ectoplasma', set:'Poing de Fusion', year:2021, number:'271/264', rarity:'Secrète alternative', language:'FR', rawMin:300, rawMax:500, graded10:900, trend:'up', score:9.5, featured:true, color:'#581c87', accent:'#fb7185', note:'Très populaire grâce à son illustration et au Pokémon représenté.' },
  { id:'lugia-v', name:'Lugia V Alt Art', pokemon:'Lugia', set:'Tempête Argentée', year:2022, number:'186/195', rarity:'Alternative', language:'FR', rawMin:180, rawMax:310, graded10:580, trend:'stable', score:9.1, color:'#0f766e', accent:'#dbeafe', note:'Valeur portée par la popularité de Lugia et une illustration marquante.' },
  { id:'mew-goldstar', name:'Mew Gold Star', pokemon:'Mew', set:'EX Île des Dragons', year:2006, number:'101/101', rarity:'Gold Star', language:'FR', rawMin:650, rawMax:2600, graded10:9000, trend:'up', score:10, color:'#be185d', accent:'#fbcfe8', note:'Gold Star vintage extrêmement recherchée. Attention aux contrefaçons.' },
  { id:'rayquaza-goldstar', name:'Rayquaza Gold Star', pokemon:'Rayquaza', set:'EX Deoxys', year:2005, number:'107/107', rarity:'Gold Star', language:'EN', rawMin:2200, rawMax:9500, graded10:45000, trend:'up', score:10, color:'#047857', accent:'#fde68a', note:'Parmi les cartes Gold Star les plus emblématiques.' },
  { id:'pikachu-van-gogh', name:'Pikachu au chapeau gris', pokemon:'Pikachu', set:'Promo Van Gogh', year:2023, number:'085', rarity:'Promo', language:'EN', rawMin:90, rawMax:170, graded10:320, trend:'stable', score:8.8, color:'#ca8a04', accent:'#fef08a', note:'Promo culturelle très connue. Vérifier soigneusement l’authenticité.' },
  { id:'charizard-151', tcgdexId:'sv03.5-199', name:'Dracaufeu ex SIR', pokemon:'Dracaufeu', set:'Écarlate et Violet 151', year:2023, number:'199/165', rarity:'Illustration spéciale rare', language:'FR', rawMin:125, rawMax:220, graded10:390, trend:'stable', score:9.0, color:'#ea580c', accent:'#fed7aa', note:'Carte moderne populaire issue d’une extension nostalgique.' },
  { id:'mew-151', name:'Mew ex Gold', pokemon:'Mew', set:'Écarlate et Violet 151', year:2023, number:'205/165', rarity:'Hyper rare', language:'FR', rawMin:18, rawMax:35, graded10:90, trend:'stable', score:7.4, color:'#db2777', accent:'#fce7f3', note:'Accessible et facile à reconnaître. Bon exemple de carte Gold moderne.' },
  { id:'magikarp-paldea', name:'Magicarpe Illustration Rare', pokemon:'Magicarpe', set:'Évolutions à Paldea', year:2023, number:'203/193', rarity:'Illustration rare', language:'FR', rawMin:85, rawMax:155, graded10:330, trend:'up', score:8.9, color:'#2563eb', accent:'#fb923c', note:'Une illustration devenue très demandée malgré un Pokémon inattendu.' },
  { id:'greninja-twilight', name:'Amphinobi ex SIR', pokemon:'Amphinobi', set:'Mascarade Crépusculaire', year:2024, number:'214/167', rarity:'Illustration spéciale rare', language:'FR', rawMin:180, rawMax:340, graded10:630, trend:'up', score:9.2, color:'#1d4ed8', accent:'#ef4444', note:'Carte récente très populaire ; surveiller la volatilité des prix.' },
  { id:'latias-surging', name:'Latias ex SIR', pokemon:'Latias', set:'Étincelles Déferlantes', year:2024, number:'239/191', rarity:'Illustration spéciale rare', language:'FR', rawMin:155, rawMax:290, graded10:520, trend:'up', score:9.0, color:'#dc2626', accent:'#f9a8d4', note:'Illustration narrative et forte demande moderne.' },
  { id:'dragonite-v', name:'Dracolosse V Alt Art', pokemon:'Dracolosse', set:'Évolution Céleste', year:2021, number:'192/203', rarity:'Alternative', language:'FR', rawMin:125, rawMax:230, graded10:410, trend:'stable', score:8.8, color:'#0284c7', accent:'#fdba74', note:'Très appréciée pour son illustration paisible et son Pokémon populaire.' },
  { id:'tyranitar-v', name:'Tyranocif V Alt Art', pokemon:'Tyranocif', set:'Styles de Combat', year:2021, number:'155/163', rarity:'Alternative', language:'FR', rawMin:115, rawMax:210, graded10:390, trend:'up', score:8.7, color:'#365314', accent:'#fde68a', note:'Surnommée la “sleepy Tyranitar”, elle garde une demande solide.' },
  { id:'blastoise-base', name:'Tortank Holo', pokemon:'Tortank', set:'Set de Base', year:1999, number:'2/102', rarity:'Holo rare', language:'FR', rawMin:80, rawMax:450, graded10:4800, trend:'stable', score:9.2, color:'#1d4ed8', accent:'#bfdbfe', note:'Un pilier vintage. La première édition et l’état changent fortement la cote.' },
  { id:'venusaur-base', name:'Florizarre Holo', pokemon:'Florizarre', set:'Set de Base', year:1999, number:'15/102', rarity:'Holo rare', language:'FR', rawMin:60, rawMax:320, graded10:3200, trend:'stable', score:8.9, color:'#15803d', accent:'#f0abfc', note:'Carte historique souvent recherchée avec Dracaufeu et Tortank.' },
  { id:'shining-gyarados', name:'Léviator Brillant', pokemon:'Léviator', set:'Neo Revelation', year:2001, number:'65/64', rarity:'Shining', language:'EN', rawMin:380, rawMax:1500, graded10:7500, trend:'up', score:9.8, color:'#b91c1c', accent:'#60a5fa', note:'Grande carte vintage Shining. Authenticité et état sont déterminants.' },
  { id:'crystal-lugia', name:'Lugia Crystal', pokemon:'Lugia', set:'Aquapolis', year:2003, number:'149/147', rarity:'Crystal', language:'EN', rawMin:1200, rawMax:6000, graded10:30000, trend:'up', score:10, color:'#0f766e', accent:'#e0f2fe', note:'Carte e-Card rarissime et prestigieuse.' },
  { id:'espeon-vmax', name:'Mentali VMAX Alt Art', pokemon:'Mentali', set:'Poing de Fusion', year:2021, number:'270/264', rarity:'Secrète alternative', language:'FR', rawMin:180, rawMax:320, graded10:580, trend:'up', score:9.0, color:'#be185d', accent:'#f9a8d4', note:'Évolition très collectionnée, illustration originale.' },
  { id:'sylveon-vmax', name:'Nymphali VMAX Alt Art', pokemon:'Nymphali', set:'Évolution Céleste', year:2021, number:'212/203', rarity:'Secrète alternative', language:'FR', rawMin:170, rawMax:300, graded10:540, trend:'stable', score:8.9, color:'#db2777', accent:'#bae6fd', note:'Une des Évolitions premium d’Évolution Céleste.' },
  { id:'leafeon-vmax', name:'Phyllali VMAX Alt Art', pokemon:'Phyllali', set:'Évolution Céleste', year:2021, number:'205/203', rarity:'Secrète alternative', language:'FR', rawMin:180, rawMax:310, graded10:560, trend:'up', score:9.0, color:'#166534', accent:'#bef264', note:'Très recherchée avec les autres évolutions d’Évoli.' },
  { id:'glaceon-vmax', name:'Givrali VMAX Alt Art', pokemon:'Givrali', set:'Évolution Céleste', year:2021, number:'209/203', rarity:'Secrète alternative', language:'FR', rawMin:160, rawMax:290, graded10:520, trend:'stable', score:8.8, color:'#0369a1', accent:'#bae6fd', note:'Belle demande collectionneur, surtout en excellent état.' },
  { id:'arceus-vstar', name:'Arceus VSTAR Gold', pokemon:'Arceus', set:'Zénith Suprême', year:2023, number:'GG70/GG70', rarity:'Galerie de Galar', language:'FR', rawMin:60, rawMax:110, graded10:220, trend:'stable', score:8.3, color:'#a16207', accent:'#fef3c7', note:'Partie d’un ensemble très apprécié avec Giratina, Dialga et Palkia.' },
  { id:'giratina-vstar', name:'Giratina VSTAR Gold', pokemon:'Giratina', set:'Zénith Suprême', year:2023, number:'GG69/GG70', rarity:'Galerie de Galar', language:'FR', rawMin:85, rawMax:145, graded10:280, trend:'up', score:8.7, color:'#5b21b6', accent:'#fde68a', note:'Souvent la plus chère du quatuor doré de Zénith Suprême.' },
  { id:'mewtwo-gx', name:'Mewtwo GX Secret', pokemon:'Mewtwo', set:'Légendes Brillantes', year:2017, number:'78/73', rarity:'Secrète', language:'FR', rawMin:85, rawMax:180, graded10:390, trend:'up', score:8.8, color:'#7e22ce', accent:'#f3e8ff', note:'Illustration “laboratoire” culte et demande durable.' },
  { id:'charizard-vmax', name:'Dracaufeu VMAX Rainbow', pokemon:'Dracaufeu', set:'La Voie du Maître', year:2020, number:'074/073', rarity:'Rainbow secrète', language:'FR', rawMin:135, rawMax:240, graded10:430, trend:'stable', score:8.8, color:'#c2410c', accent:'#f0abfc', note:'Carte emblématique de la période VMAX Rainbow.' },
  { id:'pikachu-vmax', name:'Pikachu VMAX Rainbow', pokemon:'Pikachu', set:'Voltage Éclatant', year:2020, number:'188/185', rarity:'Rainbow secrète', language:'FR', rawMin:95, rawMax:190, graded10:360, trend:'stable', score:8.6, color:'#ca8a04', accent:'#f0abfc', note:'Le célèbre “Pikachu obèse” dans sa version Rainbow.' },
  { id:'rosa-fullart', name:'Rosa Full Art', pokemon:'Dresseur', set:'Éclipse Cosmique', year:2019, number:'236/236', rarity:'Full Art secrète', language:'EN', rawMin:140, rawMax:310, graded10:650, trend:'up', score:8.9, color:'#be123c', accent:'#fbcfe8', note:'Carte Dresseur très collectionnée ; fortes différences selon la langue.' }
]

export const sets = [...new Set(cards.map(card => card.set))].sort()
export const rarities = [...new Set(cards.map(card => card.rarity))].sort()
export const years = [...new Set(cards.map(card => card.year))].sort((a,b)=>b-a)
